fos_rest:
    disable_csrf_role: IS_AUTHENTICATED_FULLY
    param_fetcher_listener: true
    routing_loader:
        default_format: json
        include_format: false
    view:
        view_response_listener:
            enabled: true
    access_denied_listener:
        json: true