jms_serializer:
    metadata:
        directories:
            KnpPaginatorBundle:
                namespace_prefix: Knp\Bundle\PaginatorBundle
                path: "%kernel.root_dir%/Resources/config/serializer/KnpPaginatorBundle"
            KnpPager:
                namespace_prefix: Knp\Component\Pager
                path: "%kernel.root_dir%/Resources/config/serializer/KnpPager"
            FosUser:
                namespace_prefix: FOS\UserBundle
                path: "%kernel.root_dir%/Resources/config/serializer/FosUser"