# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

# Import AppBundle services
imports:
    - { resource: "@AppBundle/Resources/config/services.yml" }

parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    # Change jms_serializer NamingStrategy
    # It is a workaround
    jms_serializer.camel_case_naming_strategy:
        class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy