AppBundle\Entity\Call:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        number:
            expose: true
        description:
            expose: true
        createdAt:
            expose: true
        updatedAt:
            expose: true
        deletedAt:
            expose: true
        company:
            expose: true