AppBundle\Entity\Call:
    exclusion_policy: ALL
    properties:
        id:
            groups: ["Employee", "Public"]
        number:
            groups: ["Employee", "Public"]
        createdAt:
            groups: ["Employee", "Public"]
        updatedAt:
            groups: ["Employee"]