AppBundle\Entity\Call:
    properties:
        number:
            - NotBlank: ~
            - Length:
                min: 8
                max: 20
            - Regex: '/^((\+|00)\d{1,3})?\d+$/'
        widget:
            - NotBlank: ~